### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by polarathene** [torvic9/linux49-vd#3]
Will this be made available to the AUR at some point? I searched linux49-vd but found no results. 

Will your kernel only be for LTS kernels? 

Does this integrate with Manjaro's kernel manager(listed once installed) + GRUB Advanced kernel selection?

**Comment by torvic9** [comment]
I don't have an AUR account anymore.
I will only do LTS kernels, so 4.9 only at the moment. I will update 4.4 one last time with the next releease.
No, there's no integration in Manjaro's kernel manager. linux49-vd is completely independent of Manjaro. However, it will nicely integrate into grub without overwriting  existing Manjaro kernels, so you can have my kernel installed alongside Manjaro kernels.
