### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mac-linux-free** [torvic9/linux49-vd#4]
hi torvic,

i have an build eror

`Hunk #6 succeeded at 4720 (offset 14 lines).
5 out of 6 hunks FAILED -- saving rejects to file block/cfq-iosched.c.rej
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...
`

**Comment by torvic9** [comment]
Thanks. I haven't had the time to test yet, I was in a hurry.
The error is probably due to the "block-disable-cfq" patch. Please disable it in PKGBUILD and try again.
